/* GENERATED by workspace/tests/build-logscrub.mjs -- do not edit.
 * Source of truth: site-extra/redact.html -> workspace/tests/core.mjs
 */
var DETECTORS = [
  {g:"Credentials", id:"privkey", label:"Private key blocks", tag:"PRIVATE_KEY", on:true,
   re:/-----BEGIN(?: [A-Z0-9]+)* PRIVATE KEY-----[\s\S]*?-----END(?: [A-Z0-9]+)* PRIVATE KEY-----/g},
  {g:"Credentials", id:"jwt", label:"JWTs", tag:"JWT", on:true,
   re:/\beyJ[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{4,}/g},
  {g:"Credentials", id:"aws", label:"AWS access key IDs", tag:"AWS_KEY", on:true,
   re:/\b(?:AKIA|ASIA|ABIA|ACCA|AIDA|AGPA|AROA|ANPA|ANVA|A3T[A-Z0-9])[A-Z0-9]{16}\b/g},
  {g:"Credentials", id:"gh", label:"GitHub tokens", tag:"GITHUB_TOKEN", on:true,
   re:/\bgh[pousr]_[A-Za-z0-9]{30,255}\b/g},
  {g:"Credentials", id:"slack", label:"Slack tokens and webhooks", tag:"SLACK_TOKEN", on:true,
   re:/\bxox[abprse]-[A-Za-z0-9-]{10,}|https:\/\/hooks\.slack\.com\/services\/[A-Za-z0-9\/+_-]{20,}/g},
  {g:"Credentials", id:"stripe", label:"Stripe keys", tag:"STRIPE_KEY", on:true,
   re:/\b[srp]k_(?:live|test)_[A-Za-z0-9]{10,}\b/g},
  {g:"Credentials", id:"llm", label:"OpenAI / Anthropic keys", tag:"LLM_API_KEY", on:true,
   re:/\bsk-(?:ant-|proj-|or-v1-)?[A-Za-z0-9_-]{20,}\b/g},
  {g:"Credentials", id:"google", label:"Google API keys", tag:"GOOGLE_API_KEY", on:true,
   re:/\bAIza[A-Za-z0-9_-]{35}\b/g},
  {g:"Credentials", id:"pkgtok", label:"npm / PyPI / SendGrid tokens", tag:"PACKAGE_TOKEN", on:true,
   re:/\bnpm_[A-Za-z0-9]{36}\b|\bpypi-[A-Za-z0-9_-]{16,}|\bSG\.[A-Za-z0-9_-]{16,}\.[A-Za-z0-9_-]{16,}/g},
  {g:"API keys", id:"vendorpfx", label:"Vendor-prefixed tokens (GitLab, Shopify, Atlassian, Hugging Face, ...)", tag:"VENDOR_TOKEN", on:true,
   /* Tokens whose vendor stamps a distinctive prefix on them, so they are
      identifiable with no key name anywhere nearby. Each alternative is kept
      tight to the real published shape; loose ones (Mailgun's bare "key-",
      Cloudflare's unprefixed 40-char tokens) are deliberately left out
      because they cannot be told from ordinary text. See "What it misses". */
   re:/\bgithub_pat_[A-Za-z0-9_]{50,}\b|\bgl(?:pat|ptt|rt|soat|cbt|dt|ft|imt|oat|agent)-[A-Za-z0-9_-]{20,}|\bdo[oprt]_v1_[A-Za-z0-9]{32,}\b|\bshp(?:at|ss|ca|pa)_[A-Fa-f0-9]{32}\b|\bsq0[a-z]{3}-[A-Za-z0-9_-]{20,}|\bATATT[A-Za-z0-9_=-]{20,}|\bfigd_[A-Za-z0-9_-]{20,}|\blin_api_[A-Za-z0-9]{20,}|\bhf_[A-Za-z0-9]{30,}\b|\bvercel_blob_rw_[A-Za-z0-9_]{24,}|\bfm2_[A-Za-z0-9+\/=_-]{20,}/g},
  {g:"Credentials", id:"bearer", label:"Bearer / Basic auth headers", tag:"AUTH_TOKEN", on:true,
   re:/\b(?:Bearer|Basic|Token)\s+([A-Za-z0-9._~+\/=-]{12,})/gi, groups:[1]},
  {g:"Credentials", id:"urlcred", label:"Passwords inside URLs", tag:"PASSWORD", on:true,
   re:/\b[a-zA-Z][a-zA-Z0-9+.-]*:\/\/[^\s:@\/]{0,64}:([^\s@\/]{1,128})@/g, groups:[1],
   /* A connection string in a README or a .env.example carries a placeholder, not
      a password. Same structural set the assignment detector skips, so the two
      cannot drift apart, plus the __UPPER__ form that .env.example files use. */
   skip:/^(?:\*+|x+|\.{3,}|<[^>]*>|\[[A-Z_]+\d*\]|\$\{?[A-Za-z_]\w*\}?|__[A-Za-z][A-Za-z0-9_]*__|your[_-]?[a-z]*[_-]?here|changeme|placeholder|insert[_-]?[a-z]+[_-]?here)$/i},
  {g:"Credentials", id:"assign", label:"password= / token= / secret= assignments", tag:"SECRET", on:true,
   re:/\b(?<!\$)[A-Za-z0-9_.-]*(?:password|passwd|pwd|secret(?![_-]?(?:name|uri|url|endpoint)\b)|token(?![_-]?(?:name|uri|url|endpoint)\b)|api[_-]?key|apikey|access[_-]?key|auth(?!ors?\b)|credential(?![_-]?(?:name|uri|url|endpoint)\b)|client[_-]?secret|session[_-]?id|cookie)[A-Za-z0-9_.-]*(?:\\?")?(?:\s*[:=]>?\s*(?:\\"([^"\\\n]{3,})\\"|"([^"\n]{3,})"|'([^'\n]{3,})')|[ \t]*[:=]>?[ \t]*(?![^\s\d!-\/:-@\[-`{-~]{3,19}\s+\S)([^\s,;&"'\]}]{3,}))/gi,
   groups:[1,2,3,4],
   /* Skip non-secret values: booleans, obvious placeholders, auth *scheme*
      words, so "Authorization: Bearer <jwt>" keeps the word Bearer and lets the
      dedicated header detector take just the token -- and, from wake 034, the
      log-status vocabulary. "auth", "token" and "secret" are subsystem tags in
      half the loggers in the world, so "INFO token: refreshed" looked exactly
      like an assignment and the tool replaced the word "refreshed" with
      [SECRET_1]. The lookahead above kills the multi-word form ("auth: user
      jsmith logged in" is prose, not a value); this list kills the one-word
      form. Neither costs recall: a value with a digit, mixed case or 20+
      characters still matches, so letmein, hunter2 and
      correcthorsebatterystaple are all still caught. */
   skip:/^(?:true|false|null|none|nil|undefined|yes|no|\*+|x+|\.{3,}|<[^>]*>|\[[A-Z_]+\d*\]?|redacted|masked|hidden|scrubbed|refreshed|rotated|enabled|disabled|failed|failure|success|succeeded|expired|accepted|denied|granted|revoked|valid|invalid|missing|required|created|updated|deleted|started|stopped|skipped|cached|error|warning|unknown|pending|active|inactive|complete|completed|ok|bearer|basic|token|digest|negotiate|oauth|apikey|\$\{?[A-Za-z_]\w*\}?|your[_-]?[a-z]*[_-]?here|changeme|placeholder|insert[_-]?[a-z]+[_-]?here)$/i},

  {g:"Credentials", id:"gcpsa", label:"Google service-account key fields", tag:"GCP_SA_KEY", on:true,
   re:/"private_key_id"\s*:\s*"([A-Za-z0-9]{16,64})"/g, groups:[1]},
  {g:"Credentials", id:"azure", label:"Azure storage keys and SAS signatures", tag:"AZURE_KEY", on:true,
   re:/\bAccountKey=([A-Za-z0-9+\/=]{40,})|[?&]sig=([A-Za-z0-9%+\/=]{24,})|\b(?<!sha\d{3}-)([A-Za-z0-9+\/]{86}==)/gi, groups:[1,2,3]},
  {g:"Credentials", id:"sentry", label:"Sentry DSN keys", tag:"SENTRY_KEY", on:true,
   re:/https?:\/\/([A-Za-z0-9]{16,})@[A-Za-z0-9.-]*sentry\.io\b/gi, groups:[1]},
  {g:"Credentials", id:"bottok", label:"Telegram / Discord / Twilio tokens", tag:"BOT_TOKEN", on:true,
   re:/\b\d{8,10}:AA[A-Za-z0-9_-]{32,35}\b|bot\d{8,10}:AA[A-Za-z0-9_-]{32,35}\b|\bMT[A-Za-z0-9_-]{22,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{25,}\b|\b(?:AC|SK)[a-f0-9]{32}\b/g},
  {g:"Credentials", id:"k8ssec", label:"Kubernetes secret / docker config blobs", tag:"K8S_SECRET", on:true,
   re:/(?:tls\.key|dockerconfigjson|dockercfg)"?\s*:\s*"?([A-Za-z0-9+\/=]{20,})"?/g, groups:[1]},
  {g:"Credentials", id:"yamlblock", label:"YAML block-scalar secrets (key: | on its own line)", tag:"SECRET", on:true,
   /* key: |  or  key: >  puts the value on the following indented lines, where
      the ordinary assignment detector cannot see it. Captures the whole
      indented block. */
   re:/^[ \t]*[A-Za-z0-9_.-]*(?:password|passwd|secret|token|api[_-]?key|apikey|access[_-]?key|credential|client[_-]?secret|private[_-]?key)[A-Za-z0-9_.-]*[ \t]*:[ \t]*[|>][+-]?[ \t]*\n((?:[ \t]+\S.*(?:\n(?=[ \t]+\S))?)+)/gim,
   groups:[1]},
  {g:"Credentials", id:"clicred", label:"Credentials on command lines", tag:"SECRET", on:true,
   re:/(?:^|\s)-u\s+[^\s:"']{1,64}:([^\s"']{1,128})|--(?:password|passwd|token|api-key|apikey|secret|access-key)(?:=|\s+)([^\s"']{3,})/gi,
   groups:[1,2],
   skip:/^(?:true|false|null|none|nil|undefined|yes|no|\*+|x+|\.{3,}|<[^>]*>|\[[A-Z_]+\d*\]|\$\{?[A-Za-z_]\w*\}?|\d{1,6})$/i},
  {g:"Personal data", id:"email", label:"Email addresses", tag:"EMAIL", on:true,
   /* The password half of "scheme://user:pass@host.tld" has the shape of an
      address and is not one. The password detector covers that position; when it
      declines (a placeholder in a README) nothing else should take it instead. */
   /* Unicode, not ASCII: an address may be internationalised on either side
      (RFC 6531 local parts, IDN domains). \b is defined on [A-Za-z0-9_], so it
      cannot assert a boundary next to a non-Latin letter -- it silently fails
      to match rather than matching wrongly. Explicit lookarounds instead. */
   re:/(?<!:\/\/[^\s@\/]{0,64}:)(?<![\p{L}\p{N}._%+-])[\p{L}\p{N}._%+-]+@[\p{L}\p{N}](?:[\p{L}\p{N}-]*[\p{L}\p{N}])?(?:\.[\p{L}\p{N}](?:[\p{L}\p{N}-]*[\p{L}\p{N}])?)*\.[\p{L}]{2,24}(?![\p{L}\p{N}-])/gu},
  {g:"Personal data", id:"card", label:"Payment cards (Luhn-checked)", tag:"CARD", on:true,
   re:/\b(?:\d[ -]?){12,18}\d\b/g, validate:cardNumber},
  {g:"Personal data", id:"ssn", label:"US social security numbers", tag:"SSN", on:true,
   re:/\b(?!000|666|9\d\d)\d{3}-(?!00)\d{2}-(?!0000)\d{4}\b/g},
  {g:"Personal data", id:"homedir", label:"Usernames in file paths", tag:"USER", on:true,
   /* \p{L}, not A-Za-z: a person whose name is not spelled in Latin letters
      still has a home directory, and an ASCII-only class leaves their name in
      the log. The separator that ends the capture is / or \, never a letter. */
   re:/(?:\/(?:Users|home)\/|[A-Za-z]:\\Users\\)([\p{L}\p{N}._-]{2,32})/gu, groups:[1],
   skip:/^(?:root|admin|ubuntu|runner|user|shared|public|all|default|node|www-data)$/i},
  {g:"Personal data", id:"phone", label:"Phone numbers (noisy)", tag:"PHONE", on:false,
   re:/(?:\+\d{1,3}[ .-]?)?(?:\(\d{2,4}\)[ .-]?|\d{2,4}[ .-])\d{3,4}[ .-]\d{3,4}\b/g},

  {g:"Network and machine", id:"ipv4", label:"Public IPv4 addresses", tag:"IP", on:true,
   re:/\b(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\b/g,
   skip:/^(?:127\.|255\.255|10\.|192\.168\.|172\.(?:1[6-9]|2\d|3[01])\.|169\.254\.|\d{1,3}\.0\.0\.0$)/},
  {g:"Network and machine", id:"ipv6", label:"IPv6 addresses", tag:"IPV6", on:true,
   /* Shape first, then a real validator. A loose colon-group regex alone matches
      every syslog timestamp ("09:14:02") and still misses the compressed form
      that real addresses actually use, so the shape is deliberately permissive
      and ipv6ok() decides. */
   re:/(?<![\w:.])(?=[0-9A-Fa-f:]*:[0-9A-Fa-f:]*:)[0-9A-Fa-f]{0,4}(?::[0-9A-Fa-f]{0,4}){2,7}(?![\w:])/g,
   skip:/^(?:::1|fe80:)/i, validate:ipv6ok},
  {g:"Network and machine", id:"mac", label:"MAC addresses", tag:"MAC", on:true,
   /* Six colon-separated hex pairs is also the first six bytes of every
      certificate fingerprint, GPG key id and TLS debug dump -- a run that is
      longer than a MAC and gets chopped into several fake ones. So the match
      must not be a slice of a longer colon-hex run in either direction. */
   re:/(?<![0-9A-Fa-f]:)\b(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}\b(?!:[0-9A-Fa-f])/g},
  {g:"Network and machine", id:"uuid", label:"UUIDs", tag:"UUID", on:false,
   re:/\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b/g},
  {g:"Network and machine", id:"hexblob", label:"Long high-entropy strings", tag:"HIGH_ENTROPY", on:false,
   re:/\b[A-Za-z0-9+\/_-]{32,}={0,2}/g, validate:looksRandom}
];

function luhn(s){
  var d = s.replace(/[ -]/g,"");
  if(!/^\d{13,19}$/.test(d)) return false;
  var sum=0, alt=false;
  for(var i=d.length-1;i>=0;i--){
    var n=+d[i];
    if(alt){ n*=2; if(n>9) n-=9; }
    sum+=n; alt=!alt;
  }
  return sum%10===0;
}

/* Luhn alone is not enough, and the gap is not small: a Luhn check passes one in
   ten of EVERY long integer, and computing is full of them -- nanosecond epochs,
   Snowflake ids, Kafka offsets, database bigints. It also passes a run of zeros,
   which is exactly OpenTelemetry's "no parent span" sentinel, so bare Luhn flags
   a span id in every distributed trace anyone pastes. So a Luhn-valid digit run
   is only a card if some network actually issues that prefix at that length. */
function cardNumber(s){
  var d = s.replace(/[ -]/g,"");
  if(!luhn(d)) return false;
  var n = d.length;
  return (/^4/.test(d)                                  && (n===13||n===16||n===19))  /* Visa */
      || (/^(5[1-5]|2[2-7])/.test(d)                    && n===16)                    /* Mastercard */
      || (/^3[47]/.test(d)                              && n===15)                    /* Amex */
      || (/^3(0[0-5]|[689])/.test(d)                    && n>=14 && n<=19)            /* Diners Club */
      || (/^35/.test(d)                                 && n>=16 && n<=19)            /* JCB */
      || (/^(6011|64[4-9]|65)/.test(d)                  && n>=16 && n<=19)            /* Discover */
      || (/^62/.test(d)                                 && n>=16 && n<=19)            /* UnionPay */
      || (/^(5018|5020|5038|6304|6759|676[1-3])/.test(d) && n>=12 && n<=19);          /* Maestro */
}

/* Shannon entropy per character. Only used by the opt-in high-entropy detector,
   because on its own it is far too eager. */
function looksRandom(s){
  if(/^\d+$/.test(s)) return false;
  if(!/\d/.test(s) || !/[A-Za-z]/.test(s)) return false;
  var f={}, i;
  for(i=0;i<s.length;i++) f[s[i]]=(f[s[i]]||0)+1;
  var h=0;
  for(var k in f){ var p=f[k]/s.length; h -= p*Math.log(p)/Math.LN2; }
  return h>3.6;
}

/* A real IPv6 check, run over whatever the shape regex admitted. Either the
   address is compressed with exactly one "::" and has at most 7 explicit groups,
   or it is the full form with exactly 8. Everything else -- clock times, MAC
   addresses, durations -- fails here. */
function ipv6ok(s){
  if(s.indexOf(":::")>=0) return false;
  var halves=s.split("::"), i;
  if(halves.length>2) return false;
  if(halves.length===2){
    var a=halves[0]?halves[0].split(":"):[], b=halves[1]?halves[1].split(":"):[];
    for(i=0;i<a.length;i++) if(!a[i]) return false;
    for(i=0;i<b.length;i++) if(!b[i]) return false;
    return a.length+b.length<=7;
  }
  var p=s.split(":");
  if(p.length!==8) return false;
  for(i=0;i<8;i++) if(!p[i]) return false;
  return true;
}

/* Encodings this scanner cannot see through, and why saying so matters more
   than any detector below. Every pattern here matches a contiguous ASCII-ish
   run. A log saved as UTF-16 -- which is what Windows PowerShell 5.1 writes
   from > and Out-File by default -- stores a GitHub token as g\0h\0p\0_\0,
   so every detector misses it and the scan reports zero findings. That is
   worse than an error: it is a clean bill of health for a file full of live
   credentials. Compressed and binary payloads fail the same way. Detect the
   shape of the input and refuse to call a blind scan a pass. */
function encodingHazard(text){
  if(!text || text.length<32) return null;
  var n=Math.min(text.length,8192), even=0, odd=0, ctrl=0, bad=0, i, c;
  for(i=0;i<n;i++){
    c=text.charCodeAt(i);
    if(c===0){ if(i%2) odd++; else even++; }
    /* \t \n \r and ESC are ordinary in logs; ESC especially, because ANSI
       colour codes are everywhere and must never trip this. */
    else if((c<9 || (c>13 && c<32) || c===127) && c!==27) ctrl++;
    /* U+FFFD is what a UTF-8 decoder leaves behind when it is handed bytes
       that are not UTF-8. By the time we see the string the damage is done. */
    else if(c===0xFFFD) bad++;
  }
  var nuls=even+odd, half=n/2;
  if(nuls>n*0.2){
    if(odd>half*0.7 && even<half*0.1) return {kind:"utf16le", label:"UTF-16 LE",
      note:"This looks like UTF-16 text, which is what Windows PowerShell writes from > and Out-File by default. Secrets in it are stored with a zero byte between every character, so nothing here can match them and a clean result would mean nothing. Re-save it as UTF-8, then scan again."};
    if(even>half*0.7 && odd<half*0.1) return {kind:"utf16be", label:"UTF-16 BE",
      note:"This looks like big-endian UTF-16 text. Secrets in it are stored with a zero byte between every character, so nothing here can match them and a clean result would mean nothing. Re-save it as UTF-8, then scan again."};
  }
  /* Not UTF-8 at all: a CP1251, Shift_JIS, EUC-KR or Big5 log read with the
     default utf8 decoder. The ASCII skeleton survives, so a secret is still
     found and the result looks fine -- but every non-ASCII byte has already
     been replaced, and writing the output back destroys the log. */
  if(bad>3 && bad>n*0.02) return {kind:"undecodable", label:"not UTF-8",
    note:"This is not UTF-8. It looks like a legacy single- or double-byte encoding (CP1251, Shift_JIS, EUC-KR, Big5) that your UTF-8 decoder has already mangled: every non-ASCII character has become a replacement character before this tool ever saw it. Secrets written in ASCII are still found, but the surrounding text is gone and saving this output over the original will destroy it. Convert first -- iconv -f CP1251 -t UTF-8 -- then scan."};
  if(nuls+ctrl>n*0.08) return {kind:"binary", label:"binary or compressed",
    note:"This looks like binary or compressed data, not text. Anything readable inside it is unreadable to a pattern scanner, so a clean result would mean nothing. Decompress or decode it first, then scan the text."};
  return null;
}

function escapeRe(s){ return s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"); }
function customDetectors(){return CUSTOM;}
var CUSTOM=[];
function collect(text){
  var spans=[], dets=DETECTORS.concat(customDetectors());
  dets.forEach(function(d, prio){
    if(!d.on) return;
    var flags = d.re.flags.indexOf("d")<0 ? d.re.flags+"d" : d.re.flags;
    var re;
    try { re=new RegExp(d.re.source, flags); } catch(e){ return; }
    var m, guard=0;
    while((m=re.exec(text))!==null){
      if(++guard>20000) break;
      if(m[0]===""){ re.lastIndex++; continue; }
      var start=m.index, end=m.index+m[0].length, value=m[0];
      if(d.groups){
        var span=null;
        for(var gi=0; gi<d.groups.length; gi++){
          var idx = m.indices && m.indices[d.groups[gi]];
          if(idx){ span=idx; value=m[d.groups[gi]]; break; }
        }
        if(!span) continue;
        start=span[0]; end=span[1];
      }
      if(d.skip && d.skip.test(value)) continue;
      if(d.validate && !d.validate(value)) continue;
      spans.push({start:start, end:end, value:value, tag:d.tag, det:d.id, prio:prio});
    }
  });
  /* Resolve overlaps: leftmost wins, then the higher-priority detector,
     then the longer match. */
  spans.sort(function(a,b){
    return a.start-b.start || a.prio-b.prio || (b.end-b.start)-(a.end-a.start);
  });
  var kept=[], lastEnd=-1;
  spans.forEach(function(s){
    if(s.start>=lastEnd){ kept.push(s); lastEnd=s.end; }
  });
  return kept;
}


export {collect, DETECTORS, luhn, cardNumber, looksRandom, encodingHazard};